import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {ActionIcon, Button, Input, MultiSelect} from "@mantine/core";
import {Info, MagnifyingGlass} from "@phosphor-icons/react";
import {Loading} from "@/components/Loading";
import {Roboto_Mono} from 'next/font/google'
import {AnimationBackground} from "@/components/AnimationBackground";
import "../utils/fetchAPI"
import {Section} from "@/components/Section";

const font = Roboto_Mono({subsets: ['latin'], weight: "variable"})

export default function Home() {
    const tags = [
        {value: 'experiments and results', label: 'Experiments and Results'},
    ];

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main} style={{fontFamily: font.style.fontFamily}}>
                <div className={styles.animation}>
                    <AnimationBackground/>
                </div>
                <div className={styles.container}>
                    <div className={styles.info}>
                        <ActionIcon color="blue" size="xl" radius="xl" variant="filled">
                            <Info size={24} color="#fff" weight="light"/>
                        </ActionIcon>
                    </div>
                    <div className={styles.inputs}>
                        <Input.Wrapper label="Input arxiv URL to Research Paper"
                                       className={styles.input_box}
                                       styles={{label: {fontFamily: font.style.fontFamily}}}>
                            <Input
                                icon={<MagnifyingGlass size={24} color="#1994fb" weight="light"/>}
                                placeholder="https://arxiv.org/abs/1512.03385"
                                radius="xl"
                                size="md"
                                styles={{input: {fontFamily: font.style.fontFamily}}}
                            />
                        </Input.Wrapper>
                        <MultiSelect
                            data={tags}
                            label="Select tags"
                            searchable
                            clearable
                            radius="xl"
                            size="md"
                            nothingFound="No tags found"
                            styles={{label: {fontFamily: font.style.fontFamily}}}
                        />
                        <Button radius="xl" size="md" style={{fontFamily: font.style.fontFamily}}>
                            Summarize
                        </Button>
                    </div>
                    <div className={styles.output}>
                        <Loading/>
                        <div className={styles.content}>
                            <div className={styles.filler}>
                            </div>
                            <div className={styles.summary}>
                                <h2 className={styles.summary_caption}>Summary</h2>
                                <Section title="Experiments and Results">
                                    Nam ipsum ante, imperdiet et enim nec, fermentum ultrices sem. Aenean cursus nec
                                    turpis quis pharetra. Mauris hendrerit metus id scelerisque tincidunt. Suspendisse
                                    lacus ante, interdum et tincidunt non, faucibus in ex. Curabitur vel dolor
                                    facilisis, ultricies augue et, efficitur nisi. Quisque posuere consequat elementum.
                                    Integer sit amet rhoncus orci. Mauris sodales dolor dolor, maximus sagittis nulla
                                    congue sit amet. Quisque sit amet euismod nibh. Sed eleifend ligula pulvinar massa
                                    laoreet semper. Donec luctus mauris non faucibus volutpat. Phasellus vel porttitor
                                    eros, vel cursus felis. Cras faucibus egestas tortor non facilisis. Nullam ultricies
                                    vel nisl sit amet gravida.
                                </Section>
                                <Section title="Outcomes">
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar luctus quam,
                                    ac dignissim est consequat in. Phasellus pharetra volutpat ornare. Pellentesque
                                    interdum, purus nec lacinia tempor, eros felis volutpat lectus, vitae lobortis dui
                                    urna eu risus. Morbi finibus ante eget lacus luctus consectetur. Phasellus eu congue
                                    mi. Sed neque elit, lobortis quis tellus eu, pharetra sodales neque. Suspendisse
                                    pellentesque ipsum id nibh porttitor, nec consectetur orci sollicitudin. Nunc non
                                    nibh quis ante lacinia venenatis. Phasellus sed porta justo, quis volutpat felis.
                                    Quisque cursus erat lacus, iaculis cursus tortor consequat ac. Curabitur aliquet
                                    sapien in erat fringilla, quis egestas tellus vehicula. Nam egestas accumsan lacus
                                    ut mattis. Donec lobortis libero eu erat pellentesque, ac volutpat leo commodo.
                                    Morbi nec est laoreet, commodo tortor ut, venenatis erat. Nam eget velit purus. Sed
                                    nec convallis lectus, a porta lectus.
                                </Section>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}
