import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {ActionIcon, Button, Input} from "@mantine/core";
import {Info, MagnifyingGlass} from "@phosphor-icons/react";
import {Loading} from "@/components/Loading";
import {K2D} from 'next/font/google'
import {AnimationBackground} from "@/components/AnimationBackground";

const font = K2D({subsets: ['latin'], weight: ["400", "700"]})

export default function Home() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main} style={{fontFamily: font.style.fontFamily}}>
                <div className={styles.animation}>
                    <AnimationBackground/>
                </div>
                <div className={styles.container}>
                    <div className={styles.info}>
                        <ActionIcon color="blue" size="xl" radius="xl" variant="filled">
                            <Info size={24} color="#fff" weight="light"/>
                        </ActionIcon>
                    </div>
                    <div className={styles.inputs}>
                        <Input.Wrapper description="Input arxiv URL to Research Paper"
                                       className={styles.input_box}
                                       styles={{description: {fontFamily: font.style.fontFamily}}}>
                            <Input
                                icon={<MagnifyingGlass size={24} color="#1994fb" weight="light"/>}
                                variant="filled"
                                placeholder="https://arxiv.org/abs/1512.03385"
                                radius="xl"
                                size="md"
                                styles={{input: {fontFamily: font.style.fontFamily}}}
                            />
                        </Input.Wrapper>
                        <Button radius="xl" size="md" style={{fontFamily: font.style.fontFamily}}>
                            Upload
                        </Button>
                    </div>
                    <div className={styles.output}>
                        <Loading/>
                        <div className={styles.content}>
                            <div className={styles.filler}>

                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}
